// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: repository.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepositoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryRequest) Reset() {
	*x = GetRepositoryRequest{}
	mi := &file_repository_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryRequest) ProtoMessage() {}

func (x *GetRepositoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryRequest.ProtoReflect.Descriptor instead.
func (*GetRepositoryRequest) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepositoryRequest) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *GetRepositoryRequest) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

type GetRepositoryReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RepoName      string                 `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	OwnerName     string                 `protobuf:"bytes,2,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	StarsCount    int32                  `protobuf:"varint,4,opt,name=stars_count,json=starsCount,proto3" json:"stars_count,omitempty"`
	ForksCount    int32                  `protobuf:"varint,5,opt,name=forks_count,json=forksCount,proto3" json:"forks_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsFork        bool                   `protobuf:"varint,7,opt,name=is_fork,json=isFork,proto3" json:"is_fork,omitempty"`
	ForkedFrom    *string                `protobuf:"bytes,8,opt,name=forked_from,json=forkedFrom,proto3,oneof" json:"forked_from,omitempty"`
	OpenIssues    int32                  `protobuf:"varint,9,opt,name=open_issues,json=openIssues,proto3" json:"open_issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepositoryReply) Reset() {
	*x = GetRepositoryReply{}
	mi := &file_repository_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepositoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepositoryReply) ProtoMessage() {}

func (x *GetRepositoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_repository_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepositoryReply.ProtoReflect.Descriptor instead.
func (*GetRepositoryReply) Descriptor() ([]byte, []int) {
	return file_repository_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepositoryReply) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

func (x *GetRepositoryReply) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *GetRepositoryReply) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetRepositoryReply) GetStarsCount() int32 {
	if x != nil {
		return x.StarsCount
	}
	return 0
}

func (x *GetRepositoryReply) GetForksCount() int32 {
	if x != nil {
		return x.ForksCount
	}
	return 0
}

func (x *GetRepositoryReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *GetRepositoryReply) GetIsFork() bool {
	if x != nil {
		return x.IsFork
	}
	return false
}

func (x *GetRepositoryReply) GetForkedFrom() string {
	if x != nil && x.ForkedFrom != nil {
		return *x.ForkedFrom
	}
	return ""
}

func (x *GetRepositoryReply) GetOpenIssues() int32 {
	if x != nil {
		return x.OpenIssues
	}
	return 0
}

var File_repository_proto protoreflect.FileDescriptor

const file_repository_proto_rawDesc = "" +
	"\n" +
	"\x10repository.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\"R\n" +
	"\x14GetRepositoryRequest\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\"\xcd\x02\n" +
	"\x12GetRepositoryReply\x12\x1b\n" +
	"\trepo_name\x18\x01 \x01(\tR\brepoName\x12\x1d\n" +
	"\n" +
	"owner_name\x18\x02 \x01(\tR\townerName\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x1f\n" +
	"\vstars_count\x18\x04 \x01(\x05R\n" +
	"starsCount\x12\x1f\n" +
	"\vforks_count\x18\x05 \x01(\x05R\n" +
	"forksCount\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x17\n" +
	"\ais_fork\x18\a \x01(\bR\x06isFork\x12$\n" +
	"\vforked_from\x18\b \x01(\tH\x00R\n" +
	"forkedFrom\x88\x01\x01\x12\x1f\n" +
	"\vopen_issues\x18\t \x01(\x05R\n" +
	"openIssuesB\x0e\n" +
	"\f_forked_from2V\n" +
	"\x11RepositoryService\x12A\n" +
	"\rgetRepository\x12\x18.v1.GetRepositoryRequest\x1a\x16.v1.GetRepositoryReplyB>Z<github.com/spisladqo/golang-course/task2/collector/api/protob\x06proto3"

var (
	file_repository_proto_rawDescOnce sync.Once
	file_repository_proto_rawDescData []byte
)

func file_repository_proto_rawDescGZIP() []byte {
	file_repository_proto_rawDescOnce.Do(func() {
		file_repository_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repository_proto_rawDesc), len(file_repository_proto_rawDesc)))
	})
	return file_repository_proto_rawDescData
}

var file_repository_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_repository_proto_goTypes = []any{
	(*GetRepositoryRequest)(nil),  // 0: v1.GetRepositoryRequest
	(*GetRepositoryReply)(nil),    // 1: v1.GetRepositoryReply
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_repository_proto_depIdxs = []int32{
	2, // 0: v1.GetRepositoryReply.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: v1.RepositoryService.getRepository:input_type -> v1.GetRepositoryRequest
	1, // 2: v1.RepositoryService.getRepository:output_type -> v1.GetRepositoryReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_repository_proto_init() }
func file_repository_proto_init() {
	if File_repository_proto != nil {
		return
	}
	file_repository_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repository_proto_rawDesc), len(file_repository_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repository_proto_goTypes,
		DependencyIndexes: file_repository_proto_depIdxs,
		MessageInfos:      file_repository_proto_msgTypes,
	}.Build()
	File_repository_proto = out.File
	file_repository_proto_goTypes = nil
	file_repository_proto_depIdxs = nil
}
